### ISSUE TITLE
[🐛 Bug]: `webdriver.Firefox()` crashes as Chrome, no matter venv or not on Debian on SSH

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/selenium#2]
### What happened?

<details>
<summary>Error:</summary>

```
Traceback (most recent call last):
  File "/home/benjamin/test.py", line 13, in <module>
    browser = webdriver.Firefox()
              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/firefox/webdriver.py", line 68, in __init__
    super().__init__(command_executor=executor, options=self.options)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
```
</details>

### How can we reproduce the issue?

```shell
Not read.
```

### Relevant log output

```shell
Not read.
```

### Operating System

Not read.

### Selenium version

Not read.

### What are the browser(s) and version(s) where you see this issue?

Not read.

### What are the browser driver(s) and version(s) where you see this issue?

Not read.

**Comment by Benjamin-Loison** [comment]
I forgot to use `-headless` option.
