### ISSUE TITLE
[🚀 Feature]: Add cookies without visiting the given URL

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/selenium#3]
### Feature and motivation

For speed and more discreet reasons.

```py
browser.add_cookie({'name': 'COOKIE_NAME', 'value': 'COOKIE_VALUE'})
```
<details>
<summary>Output:</summary>

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/benjamin/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in add_cookie
    self.execute(Command.ADD_COOKIE, {"cookie": cookie_dict})
  File "/home/benjamin/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/benjamin/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: Document is cookie-averse
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5
InvalidCookieDomainError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:398:5
GeckoDriver.prototype.addCookie@chrome://remote/content/marionette/driver.sys.mjs:2120:11
```
</details>

+3

### Usage example

Not read.

**Comment by Benjamin-Loison** [comment]
Would help [Webscrap_any_website/issues/67](https://codeberg.org/Benjamin_Loison/Webscrap_any_website/issues/67).

**Comment by Benjamin-Loison** [comment]
Related to [Benjamin_Loison/firefox/issues/171](https://codeberg.org/Benjamin_Loison/firefox/issues/171).
